# -*- coding: utf-8 -*-
"""Data_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P-2QKLkgrWQC6h8DzLimo8PpydNx-saT
"""

# ---------------- CELL 1: Install dependencies ----------------
!pip install mrjob -q

import random
from datetime import datetime, timedelta

random.seed(42)

ips = [f"192.168.1.{i}" for i in range(1, 21)]
urls = ["/index.html", "/products", "/about", "/contact", "/login",
        "/checkout", "/images/logo.png", "/api/data", "/cart", "/search"]
status_codes = [200, 200, 200, 200, 301, 302, 404, 500, 403, 200]
methods = ["GET", "GET", "GET", "POST", "POST"]

def generate_log_line(base_time, offset_minutes):
    ip = random.choice(ips)
    ts = base_time + timedelta(minutes=offset_minutes, seconds=random.randint(0, 59))
    method = random.choice(methods)
    url = random.choice(urls)
    status = random.choice(status_codes)
    size = random.randint(200, 5000)
    # Apache/NGINX Common Log Format (CLF)
    log_line = f'{ip} - - [{ts.strftime("%d/%b/%Y:%H:%M:%S +0000")}] "{method} {url} HTTP/1.1" {status} {size}'
    return log_line

base_time = datetime(2026, 9, 1, 0, 0, 0)
NUM_LINES = 5000

with open("access.log", "w") as f:
    for i in range(NUM_LINES):
        # spread requests across 24 hours to simulate real traffic peaks
        offset = int(random.gauss(720, 300)) % 1440  # peak around noon-ish, wraps in a day
        f.write(generate_log_line(base_time, offset) + "\n")

print(f"Generated {NUM_LINES} log lines in access.log")

# Peek at the raw log (this is the "batch input" file, similar to Unix `head`)
!head -5 access.log

# ---------------- CELL 3: Quick Unix-tools style batch analysis (baseline, for comparison) ----------------
# Classic Unix pipeline approach (awk/sort/uniq) - mentioned in Unit 5 "Batch Processing with Unix Tools"
!awk '{print $9}' access.log | sort | uniq -c | sort -rn   # status code counts
print("\n--- Top 5 requesting IPs (Unix pipeline) ---")
!awk '{print $1}' access.log | sort | uniq -c | sort -rn | head -5

# ---------------- CELL 4: Manual MapReduce Simulation (Map -> Shuffle/Sort -> Reduce) ----------------
import re
from collections import defaultdict

LOG_PATTERN = re.compile(
    r'(?P<ip>\S+) \S+ \S+ \[(?P<time>[^\]]+)\] "(?P<method>\S+) (?P<url>\S+) \S+" (?P<status>\d+) (?P<size>\d+)'
)

def parse_line(line):
    m = LOG_PATTERN.match(line)
    if not m:
        return None
    return m.groupdict()

def read_log(path):
    with open(path) as f:
        return [line.strip() for line in f if line.strip()]

# ---- MAP PHASE ----
# Each mapper emits (key, value) pairs. We simulate 3 different analyses.
def map_ip_count(record):
    return (record["ip"], 1)

def map_status_count(record):
    return (record["status"], 1)

def map_hour_traffic(record):
    # extract hour from "01/Sep/2026:13:45:02 +0000"
    hour = record["time"].split(":")[1]
    return (hour, 1)

def map_url_count(record):
    return (record["url"], 1)

def run_map_reduce(records, map_fn):
    # MAP
    mapped = [map_fn(r) for r in records]

    # SHUFFLE & SORT: group values by key
    shuffled = defaultdict(list)
    for key, value in mapped:
        shuffled[key].append(value)

    # REDUCE: sum values per key
    reduced = {key: sum(values) for key, values in shuffled.items()}
    return reduced

# Parse log into structured records (this is the "input split" stage)
raw_lines = read_log("access.log")
records = [r for r in (parse_line(l) for l in raw_lines) if r is not None]
print(f"Parsed {len(records)} valid records out of {len(raw_lines)} lines")

# Run each MapReduce job
ip_counts = run_map_reduce(records, map_ip_count)
status_counts = run_map_reduce(records, map_status_count)
hour_traffic = run_map_reduce(records, map_hour_traffic)
url_counts = run_map_reduce(records, map_url_count)

print("\n--- Top 5 IPs by request count (MapReduce) ---")
for ip, count in sorted(ip_counts.items(), key=lambda x: -x[1])[:5]:
    print(f"{ip}: {count}")

print("\n--- HTTP Status Code Distribution (MapReduce) ---")
for status, count in sorted(status_counts.items()):
    print(f"{status}: {count}")

print("\n--- Most Requested URLs (MapReduce) ---")
for url, count in sorted(url_counts.items(), key=lambda x: -x[1])[:5]:
    print(f"{url}: {count}")

# ---------------- CELL 5: Visualize the Reduce outputs ----------------
import matplotlib.pyplot as plt

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# 1. Requests per hour (traffic pattern)
hours_sorted = sorted(hour_traffic.items(), key=lambda x: int(x[0]))
hrs = [h for h, _ in hours_sorted]
vals = [v for _, v in hours_sorted]
axes[0, 0].bar(hrs, vals, color="steelblue")
axes[0, 0].set_title("Traffic by Hour of Day (Reduce Output)")
axes[0, 0].set_xlabel("Hour")
axes[0, 0].set_ylabel("Request Count")
axes[0, 0].tick_params(axis='x', rotation=90)

# 2. Status code distribution
axes[0, 1].bar(status_counts.keys(), status_counts.values(), color="orange")
axes[0, 1].set_title("HTTP Status Code Distribution")
axes[0, 1].set_xlabel("Status Code")
axes[0, 1].set_ylabel("Count")

# 3. Top 5 IPs
top_ips = sorted(ip_counts.items(), key=lambda x: -x[1])[:5]
axes[1, 0].barh([i for i, _ in top_ips], [c for _, c in top_ips], color="green")
axes[1, 0].set_title("Top 5 IPs by Requests")
axes[1, 0].invert_yaxis()

# 4. Top 5 URLs
top_urls = sorted(url_counts.items(), key=lambda x: -x[1])[:5]
axes[1, 1].barh([u for u, _ in top_urls], [c for _, c in top_urls], color="purple")
axes[1, 1].set_title("Top 5 Most Requested URLs")
axes[1, 1].invert_yaxis()

plt.tight_layout()
plt.savefig("mapreduce_log_analysis.png", dpi=150)
plt.show()

pipes_shim_code = '''
import shlex
quote = shlex.quote
'''
with open("pipes.py", "w") as f:
    f.write(pipes_shim_code)

mrjob_code = '''
from mrjob.job import MRJob
import re

LOG_PATTERN = re.compile(
    r'(?P<ip>\\S+) \\S+ \\S+ \\[(?P<time>[^\\]]+)\\] "(?P<method>\\S+) (?P<url>\\S+) \\S+" (?P<status>\\d+) (?P<size>\\d+)'
)

class MRLogAnalysis(MRJob):

    def mapper(self, _, line):
        m = LOG_PATTERN.match(line)
        if m:
            yield m.group("status"), 1

    def reducer(self, key, values):
        yield key, sum(values)

if __name__ == "__main__":
    MRLogAnalysis.run()
'''

with open("mr_log_job.py", "w") as f:
    f.write(mrjob_code)

# Run the real MapReduce job (local runner simulates Hadoop-style execution)
!python mr_log_job.py access.log

# ---------------- CELL 7: Save output artifacts for the report ----------------
with open("mapreduce_results_summary.txt", "w") as f:
    f.write("STATUS CODE DISTRIBUTION\n")
    for k, v in sorted(status_counts.items()):
        f.write(f"{k}: {v}\n")
    f.write("\nTOP 5 IPs\n")
    for k, v in sorted(ip_counts.items(), key=lambda x: -x[1])[:5]:
        f.write(f"{k}: {v}\n")
    f.write("\nTOP 5 URLs\n")
    for k, v in sorted(url_counts.items(), key=lambda x: -x[1])[:5]:
        f.write(f"{k}: {v}\n")

print("Saved: mapreduce_log_analysis.png, mapreduce_results_summary.txt")

