# -*- coding: utf-8 -*-
"""Data_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IANvQcCeHTsISd4zcJ8xpjsVwz7Mk5qY
"""

!pip install networkx matplotlib -q

# ---------------- CELL 2: Build a sample graph (mini social / web-link network) ----------------
import networkx as nx
import random

random.seed(7)

# Create a directed graph simulating a small web-link / social-follow network
G = nx.DiGraph()
nodes = [f"Page_{i}" for i in range(1, 13)]
G.add_nodes_from(nodes)

# Hand-crafted edges so a few "hub" pages clearly emerge (good for demonstrating PageRank)
edges = [
    ("Page_1", "Page_2"), ("Page_1", "Page_3"), ("Page_2", "Page_3"),
    ("Page_3", "Page_1"), ("Page_4", "Page_1"), ("Page_5", "Page_1"),
    ("Page_5", "Page_4"), ("Page_6", "Page_1"), ("Page_6", "Page_7"),
    ("Page_7", "Page_1"), ("Page_7", "Page_8"), ("Page_8", "Page_1"),
    ("Page_9", "Page_1"), ("Page_9", "Page_10"), ("Page_10", "Page_1"),
    ("Page_11", "Page_1"), ("Page_11", "Page_12"), ("Page_12", "Page_1"),
    ("Page_2", "Page_1"), ("Page_4", "Page_5"), ("Page_3", "Page_4"),
]
G.add_edges_from(edges)

print(f"Graph built: {G.number_of_nodes()} vertices, {G.number_of_edges()} edges")
print("Out-degree of each vertex:", dict(G.out_degree()))

DAMPING = 0.85
NUM_VERTICES = G.number_of_nodes()
MAX_SUPERSTEPS = 50
CONVERGENCE_THRESHOLD = 1e-6

# Superstep 0 (initialization): every vertex starts with equal rank
rank = {v: 1.0 / NUM_VERTICES for v in G.nodes()}
out_degree = {v: G.out_degree(v) for v in G.nodes()}

history = []          # track rank of every vertex per superstep (for the convergence plot)
active_vertices = set(G.nodes())   # vertices that haven't "voted to halt" yet
superstep = 0

print("Superstep | Active Vertices | Max Rank Change")
while active_vertices and superstep < MAX_SUPERSTEPS:
    superstep += 1

    # ---- MESSAGE PASSING PHASE ----
    # Each vertex sends its current rank, split evenly, along its out-edges.
    incoming_messages = {v: 0.0 for v in G.nodes()}
    for v in G.nodes():
        if out_degree[v] > 0:
            share = rank[v] / out_degree[v]
            for neighbor in G.successors(v):
                incoming_messages[neighbor] += share
        else:
            # Dangling vertex (no out-links): redistribute its rank to everyone
            for u in G.nodes():
                incoming_messages[u] += rank[v] / NUM_VERTICES

    # ---- COMPUTE PHASE (each vertex updates its own state) ----
    new_rank = {}
    max_change = 0.0
    next_active = set()
    for v in G.nodes():
        new_rank[v] = (1 - DAMPING) / NUM_VERTICES + DAMPING * incoming_messages[v]
        change = abs(new_rank[v] - rank[v])
        max_change = max(max_change, change)
        # VOTE TO HALT: only stay active if this vertex is still changing
        if change > CONVERGENCE_THRESHOLD:
            next_active.add(v)

    rank = new_rank
    active_vertices = next_active
    history.append(dict(rank))

    print(f"{superstep:9d} | {len(active_vertices):15d} | {max_change:.8f}")

print(f"\nConverged after {superstep} supersteps (all vertices voted to halt)")

print("\n--- Final PageRank scores (Pregel/BSP implementation) ---")
for v, r in sorted(rank.items(), key=lambda x: -x[1]):
    print(f"{v}: {r:.5f}")

# ---------------- CELL 4: Validate against library implementation (networkx PageRank) ----------------
nx_rank = nx.pagerank(G, alpha=DAMPING)

print("Vertex    | Our BSP PageRank | networkx PageRank | Difference")
for v in sorted(rank.keys(), key=lambda x: -rank[x]):
    diff = abs(rank[v] - nx_rank[v])
    print(f"{v:9s} | {rank[v]:16.5f} | {nx_rank[v]:18.5f} | {diff:.6f}")

max_diff = max(abs(rank[v] - nx_rank[v]) for v in G.nodes())
print(f"\nMax difference from reference implementation: {max_diff:.6f}")
print("Validation PASSED - our from-scratch BSP model matches the trusted library." if max_diff < 1e-3
      else "Validation check - differences above tolerance, inspect further.")

# ---------------- CELL 5: Visualize the graph (node size = PageRank importance) ----------------
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(10, 8))
pos = nx.spring_layout(G, seed=42, k=0.9)

node_sizes = [rank[v] * 20000 for v in G.nodes()]
node_colors = [rank[v] for v in G.nodes()]

nodes_drawn = nx.draw_networkx_nodes(
    G, pos, node_size=node_sizes, node_color=node_colors,
    cmap=plt.cm.viridis, ax=ax
)
nx.draw_networkx_edges(G, pos, alpha=0.4, arrows=True, arrowsize=15, ax=ax)

# Place labels just above each node (not centered inside) so small nodes
# don't clip their own text
label_pos = {k: (v[0], v[1] + 0.06) for k, v in pos.items()}
nx.draw_networkx_labels(
    G, label_pos, font_size=9, font_color="black", ax=ax,
    bbox=dict(facecolor="white", edgecolor="none", alpha=0.7, pad=0.5)
)

plt.colorbar(nodes_drawn, ax=ax, label="PageRank Score")
ax.set_title("Graph after Pregel-style Iterative PageRank\n(Node size/color = importance)")
ax.axis("off")
plt.tight_layout()
plt.savefig("pregel_pagerank_graph.png", dpi=150)
plt.show()

# ---------------- CELL 6: Visualize convergence across supersteps ----------------
fig, ax = plt.subplots(figsize=(10, 6))

top_vertices = sorted(rank.keys(), key=lambda x: -rank[x])[:5]
for v in top_vertices:
    values = [h[v] for h in history]
    ax.plot(range(1, len(values) + 1), values, marker="o", label=v)

ax.set_xlabel("Superstep")
ax.set_ylabel("PageRank Score")
ax.set_title("Convergence of Top-5 Vertices Across BSP Supersteps\n"
             "(Illustrates why in-memory iterative processing beats chained MapReduce jobs)")
ax.legend()
ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("pregel_convergence.png", dpi=150)
plt.show()

print(f"This computation converged in {superstep} supersteps.")
print(f"A naive iterative-MapReduce implementation would launch {superstep} separate")
print("full MapReduce jobs, each re-reading/re-writing the entire graph from disk -")
print("versus a single long-running in-memory Pregel/BSP job as demonstrated above.")

# ---------------- CELL 8: Save results summary for the report ----------------
with open("pagerank_results_summary.txt", "w") as f:
    f.write("PREGEL/BSP ITERATIVE PAGERANK - RESULTS SUMMARY\n")
    f.write("=" * 50 + "\n")
    f.write(f"Vertices: {G.number_of_nodes()}, Edges: {G.number_of_edges()}\n")
    f.write(f"Converged after {superstep} supersteps\n\n")
    f.write("Final Ranking:\n")
    for v, r in sorted(rank.items(), key=lambda x: -x[1]):
        f.write(f"{v}: {r:.5f}\n")
    f.write(f"\nMax deviation from networkx reference implementation: {max_diff:.6f}\n")

print("Saved: pregel_pagerank_graph.png, pregel_convergence.png, pagerank_results_summary.txt")

